version: '3'
services:


  spring-boot:
    image: maryemkhechine/projetdevops
    container_name: devops
    ports:
      - 8089:8089
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://192.168.33.10/:3306/achatdb?useSSL=false",
            "spring.datasource.username" : "root",
            "spring.datasource.password" : "root",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'