version: "3"
services:

  achat-spring:
    image: achat-spring
    container_name: achat-spring
    ports:
      - 8089:8089
    restart: on-failure
    environment:
      SPRING_APPLICATION_JSON: '{
                  "spring.datasource.url"  : "jdbc:mysql://mysql:3306/achatdb?useSSL=false",
                  "spring.datasource.username" : "root",
                  "spring.datasource.password" : "root",
                  "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
                  "spring.jpa.hibernate.ddl-auto" : "update"
      }'